[build]
  base = "svd-ambalaj/svd-ambalaj-frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "http://localhost:5000/svdfirebase000/us-central1/api"

[functions]
  directory = "../svd-ambalaj-backend/netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "../svd-ambalaj-backend/data/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
