[build]
  base = "svd-ambalaj/svd-ambalaj-frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://api-tfi7rlxtca-uc.a.run.app"

[functions]
  directory = "../svd-ambalaj-backend/netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "../svd-ambalaj-backend/data/**"
  ]

[[plugins]]
  package = "@netlify/plugin-nextjs"
